# -*- coding: utf-8 -*-
"""0330(質數).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PI5cXerl1bcpjfhbrGzoBq0BaKM-N-p4
"""

n = eval(input("請輸入任意正整數 n = "))
print("以下為小於", n, "的所有質數：")

for i in range(2, n):
  for j in range (2, i):
    if i % j == 0:
      break
  else:
    print(i)