# -*- coding: utf-8 -*-
"""0413hw貸款.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M01l4QNeYRjWrFuw8oODdvGzfmGVagOs
"""

def loan(p,iy,ny):
  im = iy / 12 / 100  #im月利率
  nm = ny * 12  #nm月數, ny 年數
  rate = (((1+im) ** nm) * im)/(((1+im) ** nm)-1) #本息平均月攤還率
  aveamount = p * rate #每月攤還金額
  print("每月應攤還金額：", aveamount)

print("貸款試算，請注意單位")
loan(eval(input("請輸入貸款本金(元)：")), eval(input("請輸入年利率(%)：")), eval(input("請輸入貸款年限（年）：")))
#測試git
print("success")
