# -*- coding: utf-8 -*-
"""0420(第6題).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13wdCudI0YVXbJdrrEr_w9ZhXiAm2SZTP
"""

#6-52 第6題
x = input("輸入單字：") 
l = [] 
for i in x :
  l.append(i) 

l.reverse()

for i in range(len(l)):
  print(l[i])